<?php

namespace Database\Seeders;

use App\Models\Unit;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * Data bersumber dari data resmi Tendik Administrasi LLDIKTI Wilayah X (79 Pegawai).
     * - Afdalisma, SH, M.Pd (NIP 197012051992032002) sebagai Administrator.
     * - 78 Pegawai lainnya sebagai Staff pada subbagian masing-masing.
     * - Password default: Password123!
     * - Domain email resmi: @lldiktiwilayahx.kemdiktisaintek.go.id
     */
    public function run(): void
    {
        $defaultPassword = Hash::make('Password123!');

        // Cache unit records indexed by kode_unit for fast lookup
        $units = Unit::all()->keyBy('kode_unit');

        $employees = [
            [
                'nip' => '197012051992032002',
                'name' => 'Afdalisma, SH, M.Pd',
                'username' => 'afdalisma',
                'email' => 'afdalisma@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'administrator',
                'unit_code' => null,
            ],
            [
                'nip' => '196708231991032001',
                'name' => 'Ely Susanti, SE, MM',
                'username' => 'ely_susanti',
                'email' => 'ely_susanti@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'BAG-AKM',
            ],
            [
                'nip' => '196502101991032002',
                'name' => 'Febrina Fitri, SE, M.Si',
                'username' => 'febrina_fitri',
                'email' => 'febrina_fitri@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'BAG-SDPT',
            ],
            [
                'nip' => '197003081991031001',
                'name' => 'Reri Anton, ST, MM',
                'username' => 'reri_anton',
                'email' => 'reri_anton@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'POKJA-PTK',
            ],
            [
                'nip' => '196801251991032001',
                'name' => 'Tetri Aida, SE, MM',
                'username' => 'tetri_aida',
                'email' => 'tetri_aida@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'POKJA-KLB',
            ],
            [
                'nip' => '197302021998031007',
                'name' => 'Evrinaldi, S.Si',
                'username' => 'evrinaldi',
                'email' => 'evrinaldi@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'POKJA-AKM',
            ],
            [
                'nip' => '196702121992031001',
                'name' => 'Fikri Rusli, SE, MH',
                'username' => 'fikri_rusli',
                'email' => 'fikri_rusli@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'POKJA-KLB',
            ],
            [
                'nip' => '196706301989031002',
                'name' => 'Zamri, SH, MH',
                'username' => 'zamri',
                'email' => 'zamri@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-HKTL',
            ],
            [
                'nip' => '196908241991122001',
                'name' => 'Adek Irma, SH',
                'username' => 'adek_irma',
                'email' => 'adek_irma@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'POKJA-KLB',
            ],
            [
                'nip' => '196503111994031003',
                'name' => 'Edi Sastra, SE',
                'username' => 'edi_sastra',
                'email' => 'edi_sastra@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'POKJA-PTK',
            ],
            [
                'nip' => '196702221991032002',
                'name' => 'Febriyanti B, SE',
                'username' => 'febriyanti_b',
                'email' => 'febriyanti_b@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-KMH',
            ],
            [
                'nip' => '196602031987012001',
                'name' => 'Fitri Astuti, S.Sos',
                'username' => 'fitri_astuti',
                'email' => 'fitri_astuti@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-HKTL',
            ],
            [
                'nip' => '196909021992031001',
                'name' => 'Hendri Wandi, ST',
                'username' => 'hendri_wandi',
                'email' => 'hendri_wandi@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'POKJA-AKM',
            ],
            [
                'nip' => '196512151991032003',
                'name' => 'Laida Prefni, S.Kom',
                'username' => 'laida_prefni',
                'email' => 'laida_prefni@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'BAG-TU',
            ],
            [
                'nip' => '197509172002121002',
                'name' => 'Rahman, SH',
                'username' => 'rahman',
                'email' => 'rahman@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-HKTL',
            ],
            [
                'nip' => '197206221994031002',
                'name' => 'Rukman Wijaya, SE',
                'username' => 'rukman_wijaya',
                'email' => 'rukman_wijaya@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-SIKS',
            ],
            [
                'nip' => '196803201991031003',
                'name' => 'Sirjon, S.Sos',
                'username' => 'sirjon',
                'email' => 'sirjon@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-SIKS',
            ],
            [
                'nip' => '197008131992031003',
                'name' => 'Taufik, S.Sos',
                'username' => 'taufik',
                'email' => 'taufik@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'POKJA-AKM',
            ],
            [
                'nip' => '198012292010012008',
                'name' => 'Wilda Nurhayati, S.Pd, MM',
                'username' => 'wilda_nurhayati',
                'email' => 'wilda_nurhayati@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'BAG-TU',
            ],
            [
                'nip' => '196805301993032002',
                'name' => 'Ernita, S.Kom',
                'username' => 'ernita',
                'email' => 'ernita@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-HKTL',
            ],
            [
                'nip' => '196908081991031002',
                'name' => 'Gusri, SE',
                'username' => 'gusri',
                'email' => 'gusri@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-PP',
            ],
            [
                'nip' => '196708181993032004',
                'name' => 'Suhartini, S.AP',
                'username' => 'suhartini',
                'email' => 'suhartini@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'POKJA-PTK',
            ],
            [
                'nip' => '198209262008122002',
                'name' => 'Rahmi, SE, M.Si',
                'username' => 'rahmi',
                'email' => 'rahmi@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-SARPRAS',
            ],
            [
                'nip' => '198210102008122002',
                'name' => 'Zulhidayati, ST',
                'username' => 'zulhidayati',
                'email' => 'zulhidayati@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-PP',
            ],
            [
                'nip' => '198005202008121002',
                'name' => 'Budhi NK, S.Si',
                'username' => 'budhi_nk',
                'email' => 'budhi_nk@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-KMH',
            ],
            [
                'nip' => '196712311992032004',
                'name' => 'Ezi Diana Fitri, A.Md',
                'username' => 'ezi_diana_fitri',
                'email' => 'ezi_diana_fitri@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-SARPRAS',
            ],
            [
                'nip' => '198607162010122001',
                'name' => 'Fauzia Husna, S. Farm',
                'username' => 'fauzia_husna',
                'email' => 'fauzia_husna@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-KMH',
            ],
            [
                'nip' => '198504302010121002',
                'name' => 'Hamdani, S.Kom',
                'username' => 'hamdani',
                'email' => 'hamdani@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-HKTL',
            ],
            [
                'nip' => '197606032010122001',
                'name' => 'Irna Humairah, S.Si, M.Biomed',
                'username' => 'irna_humairah',
                'email' => 'irna_humairah@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-KMH',
            ],
            [
                'nip' => '196802232007012001',
                'name' => 'Murniati, SE',
                'username' => 'murniati',
                'email' => 'murniati@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-PP',
            ],
            [
                'nip' => '198309012010122003',
                'name' => 'Resa Amelia, S.Si, M.Si',
                'username' => 'resa_amelia',
                'email' => 'resa_amelia@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-KMH',
            ],
            [
                'nip' => '198107262010121002',
                'name' => 'Yofan Hamaska, S.Kom, M.Cio',
                'username' => 'yofan_hamaska',
                'email' => 'yofan_hamaska@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-PP',
            ],
            [
                'nip' => '197707092009101001',
                'name' => 'Yulmaizar, S.Pt, MP',
                'username' => 'yulmaizar',
                'email' => 'yulmaizar@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-SIKS',
            ],
            [
                'nip' => '198608082009122003',
                'name' => 'Cory Masyithah, SE',
                'username' => 'cory_masyithah',
                'email' => 'cory_masyithah@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-PP',
            ],
            [
                'nip' => '196712041991031002',
                'name' => 'Dodi, SH',
                'username' => 'dodi',
                'email' => 'dodi@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-SARPRAS',
            ],
            [
                'nip' => '198808112010122006',
                'name' => 'Adelia Pramita Sari, SE, M.S.Ak',
                'username' => 'adelia_pramita_sari',
                'email' => 'adelia_pramita_sari@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'BAG-TU',
            ],
            [
                'nip' => '198308082010121003',
                'name' => 'Haris Roberto, S.I.Kom, M.I.Kom',
                'username' => 'haris_roberto',
                'email' => 'haris_roberto@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'BAG-TU',
            ],
            [
                'nip' => '197305092008032002',
                'name' => 'Anita, Spd, M.A',
                'username' => 'anita',
                'email' => 'anita@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'POKJA-KLB',
            ],
            [
                'nip' => '197805032005011003',
                'name' => 'Eri Suryadi, S.P',
                'username' => 'eri_suryadi',
                'email' => 'eri_suryadi@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'POKJA-PTK',
            ],
            [
                'nip' => '196608121991032002',
                'name' => 'Gusnimar',
                'username' => 'gusnimar',
                'email' => 'gusnimar@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-SARPRAS',
            ],
            [
                'nip' => '198802252015041002',
                'name' => 'Jerry Citra, S.Kom',
                'username' => 'jerry_citra',
                'email' => 'jerry_citra@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-SIKS',
            ],
            [
                'nip' => '199105072015041002',
                'name' => 'Kasreno Ofet Mei, S.IP',
                'username' => 'kasreno_ofet_mei',
                'email' => 'kasreno_ofet_mei@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-KMH',
            ],
            [
                'nip' => '199205172015042001',
                'name' => 'Meiti Utami, S.Kom',
                'username' => 'meiti_utami',
                'email' => 'meiti_utami@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'BAG-TU',
            ],
            [
                'nip' => '198905182015041003',
                'name' => 'Ori Adrian, S.Kom',
                'username' => 'ori_adrian',
                'email' => 'ori_adrian@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-SIKS',
            ],
            [
                'nip' => '198910312015042002',
                'name' => 'Putri Prima Yulda, S.Hum',
                'username' => 'putri_prima_yulda',
                'email' => 'putri_prima_yulda@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-KMH',
            ],
            [
                'nip' => '196708311993031002',
                'name' => 'Alam Yusra',
                'username' => 'alam_yusra',
                'email' => 'alam_yusra@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-KMH',
            ],
            [
                'nip' => '196807081992031001',
                'name' => 'Rida Erizal',
                'username' => 'rida_erizal',
                'email' => 'rida_erizal@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-HKTL',
            ],
            [
                'nip' => '198906142015042003',
                'name' => 'Rina Wahyuni, S.I.Kom',
                'username' => 'rina_wahyuni',
                'email' => 'rina_wahyuni@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'POKJA-KLB',
            ],
            [
                'nip' => '196801261991032001',
                'name' => 'Rismayenti',
                'username' => 'rismayenti',
                'email' => 'rismayenti@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-SARPRAS',
            ],
            [
                'nip' => '198109142010121003',
                'name' => 'Wandi, S.Kom',
                'username' => 'wandi',
                'email' => 'wandi@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-PP',
            ],
            [
                'nip' => '199101122015042002',
                'name' => 'Andika Persia, S.I.Kom',
                'username' => 'andika_persia',
                'email' => 'andika_persia@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-HKTL',
            ],
            [
                'nip' => '198604092015041002',
                'name' => 'Zul Ikram, S.Si',
                'username' => 'zul_ikram',
                'email' => 'zul_ikram@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-KMH',
            ],
            [
                'nip' => '198908142010122001',
                'name' => 'Agnes Fitriani, S.Kom',
                'username' => 'agnes_fitriani',
                'email' => 'agnes_fitriani@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-KMH',
            ],
            [
                'nip' => '197810172010121002',
                'name' => 'Henri Ilham Caniago, S.Kom',
                'username' => 'henri_ilham_caniago',
                'email' => 'henri_ilham_caniago@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-SIKS',
            ],
            [
                'nip' => '198608122010122006',
                'name' => 'Nurhayati, S.Kom',
                'username' => 'nurhayati',
                'email' => 'nurhayati@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-SIKS',
            ],
            [
                'nip' => '197712282010122002',
                'name' => 'Ratna Jimmi Lasmini, S.Kom',
                'username' => 'ratna_jimmi_lasmini',
                'email' => 'ratna_jimmi_lasmini@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'BAG-TU',
            ],
            [
                'nip' => '196806092007011002',
                'name' => 'Syahril, SH',
                'username' => 'syahril',
                'email' => 'syahril@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'POKJA-KLB',
            ],
            [
                'nip' => '198308102010122002',
                'name' => 'Ari Mega Suryani, S.Kom',
                'username' => 'ari_mega_suryani',
                'email' => 'ari_mega_suryani@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'POKJA-KLB',
            ],
            [
                'nip' => '198610142009121003',
                'name' => 'Albert Oktavian, SE',
                'username' => 'albert_oktavian',
                'email' => 'albert_oktavian@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-KMH',
            ],
            [
                'nip' => '198110252010121002',
                'name' => 'Putra Heriyadi, A.Md',
                'username' => 'putra_heriyadi',
                'email' => 'putra_heriyadi@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'POKJA-AKM',
            ],
            [
                'nip' => '198904032019031014',
                'name' => 'Afrizal, SH',
                'username' => 'afrizal',
                'email' => 'afrizal@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'POKJA-KLB',
            ],
            [
                'nip' => '198804022019031016',
                'name' => 'Apandi, ST',
                'username' => 'apandi',
                'email' => 'apandi@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-HKTL',
            ],
            [
                'nip' => '198806272019031018',
                'name' => 'Arifta Surya, S.kom',
                'username' => 'arifta_surya',
                'email' => 'arifta_surya@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'POKJA-PTK',
            ],
            [
                'nip' => '199502052019032020',
                'name' => 'Maritsa Febra Gemaya, SE',
                'username' => 'maritsa_febra_gemaya',
                'email' => 'maritsa_febra_gemaya@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-PP',
            ],
            [
                'nip' => '198803282019032015',
                'name' => 'Setriamela Marissa, SE',
                'username' => 'setriamela_marissa',
                'email' => 'setriamela_marissa@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-PP',
            ],
            [
                'nip' => '198605242010122008',
                'name' => 'Suci Rahmadani, A. Md',
                'username' => 'suci_rahmadani',
                'email' => 'suci_rahmadani@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-KMH',
            ],
            [
                'nip' => '198706122009122005',
                'name' => 'Wenny Aryan, S.Sos',
                'username' => 'wenny_aryan',
                'email' => 'wenny_aryan@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'BAG-TU',
            ],
            [
                'nip' => '198705032022031003',
                'name' => 'Mukhlis, Spd',
                'username' => 'mukhlis',
                'email' => 'mukhlis@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'POKJA-AKM',
            ],
            [
                'nip' => '199805032022032016',
                'name' => 'Vinny Putri Alda, S.H',
                'username' => 'vinny_putri_alda',
                'email' => 'vinny_putri_alda@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'POKJA-KLB',
            ],
            [
                'nip' => '198704112022031001',
                'name' => 'Urip Rahmanda, S.E',
                'username' => 'urip_rahmanda',
                'email' => 'urip_rahmanda@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-KMH',
            ],
            [
                'nip' => '199810202022032014',
                'name' => 'Nurhayana Thoybah, S.Psi',
                'username' => 'nurhayana_thoybah',
                'email' => 'nurhayana_thoybah@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'POKJA-KLB',
            ],
            [
                'nip' => '199601062022032013',
                'name' => 'Sabila Khaira, S.Psi',
                'username' => 'sabila_khaira',
                'email' => 'sabila_khaira@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'POKJA-KLB',
            ],
            [
                'nip' => '199303212022031005',
                'name' => 'Ridwan Fadlil, S.Pd',
                'username' => 'ridwan_fadlil',
                'email' => 'ridwan_fadlil@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-SIKS',
            ],
            [
                'nip' => '199511022022032007',
                'name' => 'Yolanda Noveliza, A.Md',
                'username' => 'yolanda_noveliza',
                'email' => 'yolanda_noveliza@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-KMH',
            ],
            [
                'nip' => '199907272022032014',
                'name' => 'Orintia Juwenti, A.Md',
                'username' => 'orintia_juwenti',
                'email' => 'orintia_juwenti@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-KMH',
            ],
            [
                'nip' => '199501292022032012',
                'name' => 'Kasih Citra Purnama, A.Md.Si',
                'username' => 'kasih_citra_purnama',
                'email' => 'kasih_citra_purnama@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'SUBBAG-KMH',
            ],
            [
                'nip' => '199912082022031003',
                'name' => 'Rezi Desfonta, A.Md',
                'username' => 'rezi_desfonta',
                'email' => 'rezi_desfonta@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'BAG-TU',
            ],
            [
                'nip' => '197701202014091002',
                'name' => 'Al Irsyad',
                'username' => 'al_irsyad',
                'email' => 'al_irsyad@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'BAG-TU',
            ],
            [
                'nip' => '197009192014091004',
                'name' => 'Yondri',
                'username' => 'yondri',
                'email' => 'yondri@lldiktiwilayahx.kemdiktisaintek.go.id',
                'role' => 'staff',
                'unit_code' => 'BAG-TU',
            ],
        ];

        foreach ($employees as $emp) {
            $unitId = $emp['unit_code'] ? ($units->get($emp['unit_code'])?->id) : null;

            User::updateOrCreate(
                ['nip' => $emp['nip']],
                [
                    'unit_id' => $unitId,
                    'name' => $emp['name'],
                    'username' => $emp['username'],
                    'email' => $emp['email'],
                    'password' => $defaultPassword,
                    'role' => $emp['role'],
                    'phone' => null,
                    'is_active' => true,
                ]
            );
        }
    }
}
