@extends('layouts.app')
@section('title','Meeting Report') @section('heading','Meeting Report') @section('subtitle','Evaluasi Bulanan Unit IT')
@section('content')
<style>.report-actions{display:flex;justify-content:flex-end;align-items:center;gap:10px;margin:0 0 18px}.report-export{height:37px;padding:0 15px;display:inline-flex;align-items:center;justify-content:center;font-size:13px}.report-actions .secondary{background:#fff;color:#2453d9;border:1px solid #cbdcf8}.report-actions .secondary:hover{background:#f1f6ff;border-color:#9dbcf3}@media(max-width:700px){.report-actions{justify-content:flex-start}.report-export{flex:1}}</style>
<div class="report-actions"><a class="button secondary report-export" href="{{ route('admin.notulen.editor') }}">Edit Minutes</a><button class="button report-export" data-report-action type="button">Export PDF</button><button class="button secondary report-export" data-report-word type="button">Export Word</button></div>
<section class="report-hero"><span class="badge">OFFICIAL MINUTES</span><span class="badge final">Finalized</span><h2>{{ $notulen['title'] ?? $meeting['title'] }}</h2><p>Wednesday, 12 August 2026 | {{ $meeting['time'] }} | {{ $meeting['location'] }} | Led by: {{ $meeting['host'] }}</p></section><section class="panel metadata"><div><label>Doc No.</label><b>{{ $report['docNo'] }}</b></div><div><label>Author</label><b>{{ $report['author'] }}</b></div><div><label>Approved By</label><b>{{ $report['approvedBy'] }}</b></div><div><label>Version</label><b>{{ $report['version'] }}</b></div></section>
<div class="report-grid"><section class="panel"><div class="attendance-head">Attendance Summary <span class="status completed" style="float:right">{{ $meeting['present'] ?? '--' }} / {{ $meeting['capacity'] ?? '--' }}</span></div><div class="attendance-body"><div class="subtitle">Total Present <span style="float:right;color:#08a758">{{ isset($meeting['present'],$meeting['capacity']) && $meeting['capacity'] > 0 ? round($meeting['present']/$meeting['capacity']*100) : 0 }}%</span></div><div class="progress"><div style="width:{{ isset($meeting['present'],$meeting['capacity']) && $meeting['capacity'] > 0 ? round($meeting['present']/$meeting['capacity']*100) : 0 }}%"></div></div><div class="subtitle">Present: {{ $meeting['present'] ?? '--' }} | Absent: {{ isset($meeting['present'],$meeting['capacity']) ? $meeting['capacity']-$meeting['present'] : '--' }}</div></div>
<div class="presence">@foreach($users as $user)<div class="participant"><span style="color:#08a758">OK</span><div class="user-avatar">{{ $user['avatar'] }}</div><div class="participant-info"><b>{{ $user['name'] }}</b><span>{{ $user['unit'] }}</span></div></div>@endforeach</div></section><section class="panel"><div class="notes-head">Meeting Minutes</div><div class="notes">@foreach($report['agenda'] as $item)<article class="agenda"><h3>{{ $item['title'] }}</h3>@foreach($item['body'] as $paragraph)<p>{{ $paragraph }}</p>@endforeach</article>@endforeach @if($notulen)<article class="agenda"><h3>Discussion & Agenda</h3><p>{{ nl2br(e($notulen['agenda'])) }}</p></article>@if(!empty($notulen['conclusion']))<article class="agenda"><h3>Conclusion / Follow-up</h3><p>{{ nl2br(e($notulen['conclusion'])) }}</p></article>@endif @endif</div></section></div>
@endsection
    